#!/usr/bin/env sh

#########################
# SUPER + ... KEYS      #
#########################

#Rofi
super + d
    rofi -show combi

#Toggle fullscreen of window
super + f
	bspc node --state \~fullscreen

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
    bspc node -s last

# set the node flags
super + ctrl + {x,y,z}
	bspc node -g {locked,sticky,private}


# Toggle pseudo tiling of window
#super + g
    #bspc node --state \~pseudo_tiled

#Oblogout
super + x
    oblogout

#Xkill
super + Escape
    xkill

#Terminal emulator
super + Return
	termite

#Keyboard dependent
#Terminal emulator
#super + KP_Enter
#	urxvt

#########################
# SUPER + SHIFT KEYS    #
#########################

#File-Manager
super + shift + Return
	thunar

#Keyboard dependent
#File-Manager
#super + shift + KP_Enter
#	thunar

#Reload bspwm
super + shift + r
	~/.config/bspwm/bspwmrc

#reload sxhkd:
super + shift + s
	pkill -USR1 -x sxhkd

#kill
super + shift + q
	bspc node -c

#Logout
super + shift + x
	bspc quit


#########################
# CONTROL + ALT KEYS    #
#########################


#########################
#VARIETY KEYS WITH PYWAL#
#########################


#########################
# CONTROL + SHIFT KEYS  #
#########################


#########################
#     SCREENSHOTS       #
#########################

#Flameshot
Print
    flameshot gui

#########################
#     MULTIMEDIA KEYS   #
#########################

#Raises volume
XF86AudioRaiseVolume
    amixer set Master 10%+

#Lowers volume
XF86AudioLowerVolume
    amixer set Master 10%-

#Mute
XF86AudioMute
    amixer -D pulse set Master 1+ toggle

#Playerctl works for Pragha, Spotify and others
#DELETE the line for mpc if you want to use playerctl
#putting a hashtag in front of the mpc line will NOT work
#mpc works for ncmpcpp

#PLAY
XF86AudioPlay
    mpc toggle
    #playerctl play-pause

#Next
XF86AudioNext
     mpc next
     #playerctl next

#previous
XF86AudioPrev
    mpc prev
    #playerctl previous

#Stop
XF86AudioStop
    mpc stop
    #playerctl stop

#Brightness up
XF86MonBrightnessUp
    xbacklight -inc 10

#Brightness down
XF86MonBrightnessDown
    xbacklight -dec 10

    

#########################
# BSPWM LAYOUT KEYS     #
#########################

#azerty keyboard layout for numbers 1-10
#{ampersand,eacute,quotedbl,apostrophe,parenleft,section,egrave,exclam,ccedilla,agrave}

#################################################################

#Focus selected desktop FOR QWERTY KEYBOARDS
# super + {1-9,0}
super + {q,w,e,r,t,y,u,i,o,p}
	bspc desktop -f '^{1-9,10}'

#Focus selected desktop	FOR AZERTY KEYBOARDS
#super + {ampersand,eacute,quotedbl,apostrophe,parenleft,section,egrave,exclam,ccedilla,agrave}
#    bspc desktop -f '^{1-9,10}'

#################################################################

#Move window to selected desktop FOR QWERTY KEYBOARDS
# super + shift + {1-9,0}
super + shift {q,w,e,r,t,y,u,i,o,p}
    id=$(bspc query -N -n); bspc node -d '^{1-9,10}'; bspc node -f ${id}}

#Move window to selected desktop FOR AZERTY KEYBOARDS
#super + shift + {ampersand,eacute,quotedbl,apostrophe,parenleft,section,egrave,exclam,ccedilla,agrave}
#    id=$(bspc query -N -n); bspc node -d ^{1-9,10}; bspc node -f ${id}}

#################################################################


#Focus selected desktop
alt + Tab
	bspc desktop -f '^{1-9,10}'

#Focus selected desktop
super + Tab
	bspc desktop -f '^{1-9,10}'

#Rotate desktop
alt + space
	bspc node @/ --rotate {90,-90}

# Focus/swap windows by direction
super + {_,shift + }{h,j,k,l}
	bspc node --{focus,swap} {west,south,north,east}

# Flip layout vertically/horizontally
super + {_,shift + }a
	bspc node @/ --flip {vertical,horizontal}

# Expand tiled space
alt + shift + {h,j,k,l}
	bspc node {@west -r -10,@south -r +10,@north -r -10,@east -r +10}

# Contract tiled space
super + ctrl + {h,j,k,l}
	bspc node {@east -r -10,@north -r +10,@south -r -10,@west -r +10}

# Increase/decrease window gap on focused desktop
super + bracket{left,right}
	bspc config -d focused window_gap $((`bspc config -d focused window_gap` {-,+} 5 ))

# Move floating window
super + alt + {_,shift + }{Left,Down,Up,Right}
	~/.config/bspwm/scripts/move-window {_,edge-}{west,south,north,east}

# set the window state
super + space
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# Focus parent/brother/first/second for preselection
super + ctrl + {e,r,t,y}
	bspc node --focus @{parent,brother,first,second}

# Preselect the splitting area for next window on leaf/parent
super + ctrl + {u,i,o,p}
	bspc node --presel-dir \~{west,south,north,east}

# Define splitting ratio for next window on leaf/parent
super + ctrl + {_,shift +}{1-9}
	bspc node {_,@/} --presel-ratio 0.{1-9}

# Cancel preselection
super + ctrl + space
	bspc node --presel-dir cancel


# Emulate i3's scratchpad
F12
	xdotool search --onlyvisible --classname scratchpad windowunmap \
	|| ( xdotool search --classname scratchpad windowmap; xdotool search --classname scratchpad windowraise; ) \
	|| ( urxvtc -name scratchpad -geometry 220x20+400+0; xdotool search --classname scratchpad windowraise; )

#########################
#        My keys        #
#########################

# Включение русской раскладки
ctrl + alt + l
	setxkbmap us,ru ,winkeys grp:caps_toggle grp_led:caps


    #----- Scratchpad -----#
# send to scratch
super + minus
  scratch-hide
# return from scratch
super + shift + minus
  scratch-show
